version: '3.7'

services:
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tomatex
      - POSTGRES_PASSWORD=tomatex
      - POSTGRES_DB=tomatex_dev

volumes:
  postgres_data:
