# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tomatex CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install python-dev libpq-dev -y
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false --local
        poetry install
    - name: Run Migrations
      run: |
        poetry run python manage.py migrate
    - name: Test with pytest
      run: |
        poetry run pytest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Deploy Application
      uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "tomatex"
        heroku_email: "me@gilsondev.in"
